[package]
name = "osrs-client-demo"
version = "0.1.0"
authors = ["Jos√©Santos <ee01149@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
